version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - .:/go/src/app
    tty: true
    env_file:
      - ./Docker/.go_env
    environment:
      - TZ=Asia/Tokyo
